### ISSUE TITLE
Build Snap on Windows through a script

### ISSUE THREAD

**Issue by jessemillar** [Snap-for-Windows/snap#2]

**Comment by jessemillar** [comment]
This'll most likely be a modification of the [Travis build pipeline](https://github.com/Snap-for-Windows/snap/blob/master/.travis.yml).

**Comment by jessemillar** [comment]
Ah. Nope. This'll be a modification of the [Makefile](https://github.com/Snap-for-Windows/snap/blob/master/Makefile).

**Comment by jessemillar** [comment]
This is complicated by the size and utility of the various shell scripts contained in the [`/scripts`](https://github.com/Snap-for-Windows/snap/tree/master/scripts) directory. The Makefile mentioned above largely exists to call those shell scripts which don't work by default on Windows.

**Comment by jessemillar** [comment]
We could potentially use CMake for generating Makefiles and [Batsh](https://github.com/BYVoid/Batsh) for writing alternative shell scripts, but this may be more trouble than it's worth. In the long run, there shouldn't be drastic changes at this point to the build process for Snap which means a write-once batch option for Windows supplementing the current Linux build process should be sufficient for our purposes.

**Comment by jessemillar** [comment]
Builds on Windows (via the [current .bat scripts](https://github.com/Snap-for-Windows/snap/tree/0b19078aa534d3099eca6ecac20162c7e87617b2/scripts)) are failing with the following error. The same code builds just fine on macOS (using the Makefile instead of our batch files), so it's not a code issue. It's gotta be a Windows problem, maybe with the way .bat sets [build parameters](https://github.com/Snap-for-Windows/snap/blob/0b19078aa534d3099eca6ecac20162c7e87617b2/scripts/build_snap.bat#L6)...?

```
# github.com/intelsdi-x/snap/control/plugin/rpc
..\..\intelsdi-x\snap\control\plugin\rpc\plugin.pb.go:768: undefined: grpc.SupportPackageIsVersion3
# github.com/intelsdi-x/snap/grpc/controlproxy/rpc
..\..\intelsdi-x\snap\grpc\controlproxy\rpc\control.pb.go:348: undefined: grpc.SupportPackageIsVersion3
```

**Comment by devingd** [comment]
Don't know if this is just my machine being weird but I had to add `
go build github.com/Masterminds/glide` to the deps script after `
go get github.com/Masterminds/glide` to get rid of the "'glide' is not a recognized command..." error. I thought running `go get` built the package after downloading unless you specifically told it not to (-d). Anyone verify this is needed or just my machine being weird?

**Comment by devingd** [comment]
Found this. Might be helpful. Haven't found out how to do the last step yet.

FAQ at the bottom:
https://github.com/grpc/grpc-go/blob/3018da5a38302cfcf6300ec9ac1e6bcd930d5b2e/README.md

Also, everything I've seen say to upgrade to version4 and I've noticed a few checks in the snap code are version3. I've updated those to 4 (locally) but as expected it throws other errors. Haven't been able to get go to install version3 even if I change the version flag on the glide.yaml file.
Note: How does global vs vendor work with Go/Glide/etc.? Looks like it's using global google.golang.org/gRPC (version4, added during `go get -d github.com/snap-for-windows/snap`) and not vendor (version3 vendor is never used when using `go get`)

**Comment by devingd** [comment]
Copying gRPC from vendor to global solves the version error. But the whole vendor and Go thing seem way screwy and lots of heated arguments about proper implementation have taken place with no real answers. Supposedly it's supposed to pull from vendor first then globally if you run the command at a certain location (standing on your head, while juggling) but I could only find one other user that posted about our same issue and he was also on Windows. I hope I'm missing something obvious and it's a much simpler fix, but my digging tonight has not been hopeful.

the next set of errors if grpc is added correctly is: 

`# command-line-arguments
.\snapteld.go:211: cannot use control.Flags (type []"github.com/urfave/cli".Flag) as type []"github.com/snap-for-windows/snap/vendor/github.com/urfave/cli".Flag in append
.\snapteld.go:212: cannot use scheduler.Flags (type []"github.com/urfave/cli".Flag) as type []"github.com/snap-for-windows/snap/vendor/github.com/urfave/cli".Flag in append
.\snapteld.go:213: cannot use rest.Flags (type []"github.com/urfave/cli".Flag) as type []"github.com/snap-for-windows/snap/vendor/github.com/urfave/cli".Flag in append
.\snapteld.go:214: cannot use tribe.Flags (type []"github.com/urfave/cli".Flag) as type []"github.com/snap-for-windows/snap/vendor/github.com/urfave/cli".Flag in append
.\snapteld.go:796: cannot use "github.com/snap-for-windows/snap/vendor/github.com/vrischmann/jsonutil".Duration literal (type "github.com/snap-for-windows/snap/vendor/github.com/vrischmann/jsonutil".Duration) as type "github.com/vrischmann/jsonutil".Duration in assignment`

but I'm calling it a night.

**Comment by thomastaylor312** [comment]
@jessemillar and @devingd, I think @mathewlk had a similar issue. There needs to be a step for restoring dependencies. Basically you are using a future version of gRPC that isn't pinned to a stable version

As for the the other errors, they look dependency related as well. I know that on a *nix machine, it installs the dependency management tool and installs all of the correct dependencies. That definitely looks like what is going on here. 

As for your other question, Go by default looks at what is in vendor first, so the `glide install` should get you to the right state. You may also want to make sure that your dependencies in your normal `$GOPATH` are not checked out on a specific git SHA. I have seen errors occur because of that as well.

**Comment by jessemillar** [comment]
@thomastaylor312 I'll check into the specific SHA thing but I doubt that's an issue since the only dependencies on my machine were there because of `go get -d github.com/intelsdi-x/snap`. Unless Snap by default is somehow grabbing a specific SHA I doubt there's an issue. We're also definitely running `glide install` in [deps.bat](https://github.com/Snap-for-Windows/snap/blob/master/scripts/deps.bat) which is called by [build_all.bat](https://github.com/Snap-for-Windows/snap/blob/master/scripts/build_all.bat).

**Comment by thomastaylor312** [comment]
Possibly related: https://github.com/mattfarina/golang-broken-vendor

**Comment by jcooklin** [comment]
@jessemillar @thomastaylor312 I was unable to reproduce the build problem when I ran build_all.bat on my Windows 10 VM.  I however notice that after running the script I was dumped in the directory (.\cmd\snaptel). 
![img](https://www.evernote.com/l/AA2KZ6jX-4lDhoIPXahXe4BQihU2Glp0h8QB/image.png)

The CLI (snaptel) was not built.  
![img](https://www.evernote.com/l/AA3EZ4WL2wdJnomCbLOvAw6bL7VEqH1hG8YB/image.png)

**Comment by jcooklin** [comment]
The `bat` files that have been created so far are great however I feel like the higher value work right now related to Windows would be packaging Snap for Windows in the form of an MSI and general documentation that could be dropped into the main README.  I feel it's fine if the Makefile is not supported on Windows and we direct devs on Windows to use the scripts directory (./scripts/build_all.sh, etc...).  

Below are some high priority work items related to build and deploy as I see it:
- [ ] Start stubbing out Windows section in the README
- [ ] Create Windows Snap package ([MSI](https://en.wikipedia.org/wiki/Windows_Installer))
  - [ ] Install snap as a service
    - [ ] What user does the service run as
    - [ ] What kind of permissions are required
  - [ ] Define where the default config should exist
    - [ ] Define the appropriate config values for windows (where should logs go etc)
---
Related to build and deploy is logging
 - [ ] Investigate Snap logging to windows event logger instead of to a file
   - [ ] Use a logrus event log hook 👉 https://github.com/aadidenko/evloghook??

These are just some suggestions.  Happy coding. 😸

**Comment by devingd** [comment]
With the acceptance/merging of pull request #29, I deem this complete. Great work @jessemillar

**Comment by jessemillar** [comment]
It was mostly @jcooklin, but thanks! I'll take any praise I can get. :stuck_out_tongue:
